name: Deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
      
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fransihsan/courses:latest

      - name: checkout
        uses: actions/checkout@master
      
      - name: login okteto
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
      - name:  "Activate personal namespace"
        uses: okteto/namespace@latest
        with:
          namespace: fransihsan
      
      - name: "create deployment"
        uses: okteto/apply@latest
        with:
          namespace: fransihsan
          manifest: deployment.yaml
      
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment go-app-deployment
